name: Chivarly Gamemode
main: fr.Cubecraftzdev.Chivarly.Main
version: 0.1.4
commands:
    Chivarly:
        description: Chivarly Gamemode
        usage: /cm
    Chivarly join:
        description: Join The Gamemode.
        usage: /cm join
    Chivarly quit:
        description: Quit The QuakeGame.
        usage: /cm quit 
    Chivarly forcestart:
        description: Forcestart the Game.
        usage: /cm forcestart 
    Chivarly setdefaultspawn:
        description: SetDefaultSpawn for The Game.
        usage: /quakecraft setdefaultspawn 
    Chivarly setdefaultspawn:
        description: setspawnrandom for The Game.
        usage: /cm setspawnrandom [x]
    Chivarly joinauto:
        description: joinauto for The Game.
        usage: /quakecraft joinauto
